### ISSUE TITLE
Expose Queue Declaration Retry Properties

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream-binder-rabbit#104]
See https://jira.spring.io/browse/AMQP-778 and https://stackoverflow.com/questions/46896243/spring-cloud-stream-sink-loses-rabbitmq-connectivity/46897095#46897095

By exposing properties for `declarationRetries` as well as the intervals, the container can be configured to stay up when the condition exists.

Also `missingQueuesFatal`.

**Comment by cagewyt** [comment]
Hi garyrussell, so glad to see someone raised this issue and thank you for your time and effort working on it. 

We encountered the same issue yesterday that we would like to set missingQueuesFatal provided by SimpleMessageListenerContainer.java in spring-amqp. However, RabbitMessageChannelBinder.java in spring cloud stream does not expose this configuration property (RabbitProperties, RabbitBindingProperties, RabbitConsumerProperties only provide a subset of the properties of spring-amqp). 

In createConsumerEndpoint method of RabbitMessageChannelBinder class, SimpleMessageListenerContainer is constructed through constructor, but applicationContext is not set (thus null). Therefore, checkMissingQueuesFatal method in  SimpleMessageListenerContainer class can't set missingQueuesFatal through global properties bean since applicationContext is null. 
`ApplicationContext applicationContext = getApplicationContext();
				if (applicationContext != null) {
					Properties properties = applicationContext.getBean("spring.amqp.global.properties", Properties.class);
					String missingQueuesFatal = properties.getProperty("smlc.missing.queues.fatal");
					if (StringUtils.hasText(missingQueuesFatal)) {
						this.missingQueuesFatal = Boolean.parseBoolean(missingQueuesFatal);
					}
				}`

A quick fix may be to call setApplicationContext in RabbitMessageChannelBinder to pass applicationContext to SimpleMessageListenerContainer. However, it will only support missingQueuesFatal property, not others. 

It will be great to expose all configuration properties of spring-amqp https://docs.spring.io/spring-amqp/reference/htmlsingle/#containerAttributes to relevant RabbitProperties of spring cloud stream, OR provide an easy way to config SimpleMessageListenerContainer (maybe through SimpleRabbitListenerContainerFactory's initializeContainer method, instead of using constructor, so client program can create a customized bean of rabbitListenerContainerFactory and set properties through rabbitListenerContainerFactory. refer to RabbitAnnotationDrivenConfiguration class in spring-boot-autoconfigure)
`      @Bean
	@ConditionalOnMissingBean(name = "rabbitListenerContainerFactory")
	public SimpleRabbitListenerContainerFactory rabbitListenerContainerFactory(
			SimpleRabbitListenerContainerFactoryConfigurer configurer,
			ConnectionFactory connectionFactory) {
		SimpleRabbitListenerContainerFactory factory = new SimpleRabbitListenerContainerFactory();
		configurer.configure(factory, connectionFactory);
		return factory;
	}`

Thank you very much for fixing this issue.

**Comment by garyrussell** [comment]
@cagewyt I have edited your post to fix the formatting; please take a look (edit) to see how to format code in github markdown.

In 2.0 we are planning on making some significant changes to the way bindings are configured; we'll consider using the container factory at that time.

Thanks for the suggestions.
