### ISSUE TITLE
 RabbitTemplate-ConfirmCallback or ReturnCallback.

### ISSUE THREAD

**Issue by gengxiaoxiaoxin** [spring-cloud/spring-cloud-stream-binder-rabbit#151]
``` yml
spring:
  rabbitmq:
    publisher-confirms: true
    publisher-returns: true`
```
``` java
rabbitTemplate.setConfirmCallback((correlationData, ack, cause) -> 
    System.out.println("ack: " + ack + ". correlationData: " + correlationData + "cause : " + cause)
);
rabbitTemplate.setReturnCallback((message, replyCode, replyText, tmpExchange, tmpRoutingKey) -> 
    System.out.println("send message failed: " + replyCode + " " + replyText);
);
```
**_When I try to send a message to a non-existing exchange, it will not trigger ConfirmCallback or ReturnCallback._**
This's the output
```
ERROR 9252 --- [ 127.0.0.1:5672] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'exchangeName2' in vhost '/', class-id=60, method-id=40)
```

**Comment by garyrussell** [comment]
See [the documentation](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RELEASE/reference/htmlsingle/index.html#rabbit-error-channels).

The connection factory must be configured for confirms and returns to be enabled.

With the rabbit binder, failed messages sent to the output binding(s) will be sent to the error channel.

If you use a rabbit template directly (instead of the binder), the callbacks will be called.

**Comment by garyrussell** [comment]
See [the documentation](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RELEASE/reference/htmlsingle/index.html#rabbit-error-channels).

With the rabbit binder, failed messages sent to the output binding(s) will be sent to the error channel.

If you use a rabbit template directly (instead of the binder), the callbacks will be called.

Sending to a non-existent exchange does not result in a returned message - only sending to an exchange that does not route the message to at least one queue results in a returned message.

**Comment by gengxiaoxiaoxin** [comment]
@garyrussell Maybe I should use a rabbit template directly and thank you for that.

**Comment by olegz** [comment]
@gengxiaoxiaoxin I am not sure I fully understand.
Could you please elaborate on your use case and what triggers sending messages to a non-existing exchange?

**Comment by gengxiaoxiaoxin** [comment]
@olegz lol.
I just delete the exhange.

**Comment by olegz** [comment]
I am not sure how to treat your response.  May be you can clarify.
Also, please change the title of the issue that it corresponds to its desription

**Comment by gengxiaoxiaoxin** [comment]
@olegz I mean delete the exchange from the rabbitmq-web-console.

**Comment by garyrussell** [comment]
Why would you do that?

**Comment by gengxiaoxiaoxin** [comment]
@garyrussell I want to test several possible abnormalities.
If some fatal error occurs, I need to roll back the transaction.

**Comment by gengxiaoxiaoxin** [comment]
@garyrussell Thanks for your kind help.
