### ISSUE TITLE
There is no option to configure the routing key for anonymous queue binding

### ISSUE THREAD

**Issue by SirWayne** [spring-cloud/spring-cloud-stream-binder-rabbit#18]
Currently the anonymous queue is always bound to all topics (#).  The topic is harcoded in RabbitMessageChannelBinder
`declareBinding(queue.getName(), BindingBuilder.bind(queue).to(exchange).with("#"));`
Spring Cloud Bus uses Spring Cloud Stream to broadcast the messages (e.g. events)

Also so :

For some use cases it might be helpful to filter messages by topic. For example multiple nodes are publishing events but not every node is interested in all of them. Is it possible to introduce a binder property to configure the routing key?

**Comment by mbogoevici** [comment]
Hi @SirWayne,

Thanks for the issue and PR. Can you provide some details about this issue? The original premise is:

> Currently the anonymous queue is always bound to all topics (#). 

In the current implementation, an anonymous queue will receive all the messages sent to a given topic exchange. Publishers add the exchange name as the routing key for the message. In your solution, the user can choose between using the hash or the routing key on the queue - however, as far as I can tell, regardless of their choice, they will receive all messages - because all messages have the same routing key. Also, it seems like being able to set the routing key explicitly (rather than a boolean flag) is a more flexible option (but it would have to be known by the publisher). 


Can you provide some detail about your use case?

Thanks,
Marius.

**Comment by SirWayne** [comment]
My first solution was, to set the public key directly with a property. But then i use the same mechanism like at the createProducerMessageHandler. So for me it's totally fine to use a new property e.g
`spring.cloud.stream.rabbit.bindings.springCloudBusInput.consumer.routing-key`

Now you can have different input routing keys for different instances. Thats the use case e.g. in a cluster environment.
Instance1:
``` 
spring.cloud.stream.bindings.springCloudBusInput.destination=eventA
spring.cloud.stream.rabbit.bindings.springCloudBusInput.consumer.prefix=exchange.
spring.cloud.stream.rabbit.bindings.springCloudBusInput.consumer.use-hash-binding-key=false
```

Instance2:
``` 
spring.cloud.stream.bindings.springCloudBusInput.destination=eventB
spring.cloud.stream.rabbit.bindings.springCloudBusInput.consumer.prefix=exchange.
spring.cloud.stream.rabbit.bindings.springCloudBusInput.consumer.use-hash-binding-key=false
```

So now the publisher can decide which instance will get the message.

**Comment by SirWayne** [comment]
I would prefer a new property for the routing key.

**Comment by mbogoevici** [comment]
@SirWayne: Still trying to understand the issue here - please bear with me.

in your example, the two applications listen to queues bound to two separate exchanges. 

Instance 1 will listen to a queue bound to the topic exchange `exchange.eventA`.
Instance 2 will listen to a queue bound to the topic exchange `exchange.eventB`.

They will not receive the same messages, even if the routing key of the queue is `#`. I believe this initial statement was the source of confusion.

> Currently the anonymous queue is always bound to all topics (#). 

The anonymous is only bound to the exchange specified via `destination`.

The publisher sends messages to an instance or another by using a different target exchange. 

Even if the routing key is set by the consumer, the producer will always set the routing key to the exchange name, i.e. messages sent to `exchange.eventA` get a routing key of `eventA`, and messages sent to `exchange.eventB` get a routing key of `eventB`.

With the suggested change of choosing between having routing key of the bound queue from `#` to `<exchangeName>`, you still get a queue that receives all the messages sent by a Spring Cloud Stream producer to a specific exchange.

**Comment by SirWayne** [comment]
Ahhh you are right the first proposal is wrong.
The second solution will work. I would like to have (cluster) instances or publisher with the same exchange, but different routing keys.
A third party application or other publishers should only handle 1 exchange and not n exchanges.

I think this is a better setup:
Instance1:
``` 
spring.cloud.stream.bindings.springCloudBusInput.destination=events
spring.cloud.stream.rabbit.bindings.springCloudBusInput.consumer.prefix=exchange.
spring.cloud.stream.rabbit.bindings.springCloudBusInput.consumer.routing-key=eventA
```

Instance2:
``` 
spring.cloud.stream.bindings.springCloudBusInput.destination=events
spring.cloud.stream.rabbit.bindings.springCloudBusInput.consumer.prefix=exchange.
spring.cloud.stream.rabbit.bindings.springCloudBusInput.consumer.routing-key=eventA
```


Instance3:
``` 
spring.cloud.stream.bindings.springCloudBusInput.destination=events
spring.cloud.stream.rabbit.bindings.springCloudBusInput.consumer.prefix=exchange.
spring.cloud.stream.rabbit.bindings.springCloudBusInput.consumer.routing-key=eventB
```

**Comment by mbogoevici** [comment]
Ok - I see the point now :) For this to work though,  I guess we'd need to have a mechanism for setting the routing key on producer side as well (and dynamically) - right now it is always 'events' so this set up will never receive messages.

**Comment by SirWayne** [comment]
Yes that would be great for a internal communication, if you can set the routing key dynamically on producer side. But even this small solution has advantages. A third party producer application, can set different routing keys which you can use the wildcard mechanism. This is hard to implement by different exchanges.

Another point is. Currenty the properties set only the consumer
For the producer you have to set antoher property for the outputchannel or?
E.g. ``` spring.cloud.stream.bindings.springCloudBusOutput.destination=MySpecialEvent ```

**Comment by mbogoevici** [comment]
Yes, you can set a different destination for the producer side 
``` spring.cloud.stream.bindings.springCloudBusOutput.destination=MySpecialEvent ```. Your mileage may vary, as Bus is a broadcast mechanism.

Depending on your use case, you may want to use Spring Cloud Stream directly (Bus is fairly opinionated in that its use case is to broadcast events - you can specificy what applications are interested, but that is filtered on the client side). 

My earlier comment was that even without a dynamic routing key property, the producer must be able to set up a different key than the default one - which is the exchange name and it is always set like that. In your scenario, once your consumers use routing keys such as `eventA` or `eventB`, they will stop receiving messages altogether, because the routing key is always `event`. We need to make that customizable as well.

**Comment by SirWayne** [comment]
I know, that the bus could filter events by the client side. But this is in our use case very expensive.
So this dynamic property is the first step and would help us.

For the spring cloud bus it would be very nice if you can set the destination (exchange) diretly to the event (RemoteApplicationEvent). But i think this is much more effort.

**Comment by maharavindran** [comment]
i have an usecase similar to this : 

consumer 1:should receive events for exchange.event.specificevent
consumer 2: should receive events for exchange.event.*
consumer 3: should receive events for #.someevent

so based on the requirement my destination(topic) might change and i have to configure the subscription of the consumer dynamically based on the destination names. Currently i don't find any property to configure this(like routing -key.even though i configure different routing keys once you enable the property i will get all messages to that destination) .i need the ability to play with * and # on the destination names.Can someone help me with this ?

**Comment by sabbyanandan** [comment]
This has been addressed via: https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/34.
