### ISSUE TITLE
Reconsider importing Boot's auto-configuration

### ISSUE THREAD

**Issue by wilkinsona** [spring-cloud/spring-cloud-stream-binder-rabbit#187]
RabbitServiceAutoConfiguration uses `@Import` to pull in Boot's `RabbitAutoConfiguration`: https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/d4fbad5672140a9c5d3173df0e9a05bb58e7b994/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/config/RabbitServiceAutoConfiguration.java#L132

This has [caused some confusion](https://github.com/spring-projects/spring-boot/issues/14906) as it means that `@SpringBootApplication(exclude = {RabbitAutoConfiguration.class})` doesn't work. It also has the potential to cause ordering problems as other auto-configurations that have used `@AutoConfigureBefore(RabbitAutoConfiguration.class)` or `@AutoConfigureAfter(RabbitAutoConfiguration.class)` won't be ordered correctly.

More generally, other than when ordering auto-configurations using `@AutoConfigureBefore` or `@AutoConfigureAfter` or excluding them, I would recommend not depending on Boot's auto-configuration classes directly.

**Comment by garyrussell** [comment]
I think we only use the properties anyway so I am not sure why this is needed at all.

**Comment by bono007** [comment]
I recently ran into this issue while debugging one of our applications. I know this issue has been dormant for quite a while. I did some digging to see about submitting a merge request addressing the concern(s). I wanted to share my findings.

So, a couple of things are at play here:

**1)** As noted in this related [issue](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/188), `RabbitServiceAutoConfiguration` is not an auto-configuration, but rather a [binder implementation](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#spring-cloud-stream-overview-binder-api) which is loaded by the Binder SPI. As such, it does not partake in the typical Spring Boot Auto-Configuration flow. It is loaded instead in its own lightweight app context whose configuration classes are composed of the csv list of classes in the binder entry in the `META-INF/spring.binders` file. In this case the `RabbitServiceAutoConfiguration` only. 

As suggested in the above related ticket, this Binder implementation config should be renamed to have the "AutoConfiguration" removed from it. A breaking change for sure. Will need to do this in a minor release.

**2)**  

> I think we only use the properties anyway so I am not sure why this is needed at all.

The RabbitServiceAutoConfiguration actually needs both ConnectionFactory and RabbitTemplate - which RabbitAutoConfiguration provides. The RabbitAutoConfiguration class is simply being used for the convenience of configuring these 2 things (not as an auto-config - hence the direct @Import). 

I think the fix here is to create a Spring Cloud Stream Rabbit Binder specific RabbitConfiguration that does these 2 things - thereby breaking the dependence on the Spring Boot RabbitAutoConfiguration. 

Wanted to get some thoughts before submitting a code proposal for the above.

@wilkinsona @garyrussell wdyt?

**Comment by wilkinsona** [comment]
I'm not sufficiently familiar with the code to comment on the best way to fix this so I'll defer to @garyrussell and others.

**Comment by garyrussell** [comment]
Sadly, its a ditto from me 😦 

I think this should be completely reworked - we no longer use the old cloud connectors for cloud foundry; I think [cfenv](https://spring.io/blog/2019/02/15/introducing-java-cfenv-a-new-library-for-accessing-cloud-foundry-services) is used instead.

cc/ @sobychacko

**Comment by bono007** [comment]
> we no longer use the old cloud connectors for cloud foundry

I was wondering about this since Spring Cloud Connectors is in maintenance mode. What is the deprecation plan for Spring Cloud Connectors in Spring Cloud Stream? 

> I think cfenv is used instead.

And yeh, the output of `java-cfenv` is set of `spring.rabbitmq.*` auto-config props so it would definitely rely on Spring Boot auto-config. Also, in order to use `java-cfenv` with the current impl, the following property would need to be set to disable the cloud auto-config:
```yaml
spring.cloud.stream.overrideCloudConnectors: true
```
This gets even more interesting wrt to connecting to multiple systems where `java-cfenv` only handles a single set of auto-config props (IIRC). 


Ok... some thoughts of things that we may want to do:
1. Create an issue around Spring Cloud Connectors deprecation/maintenance for Spring Cloud Stream
2.  Possibly mark the cloud connector auto-config deprecated here in the Rabbit binder config
3. Document how to use `java-cfenv` (single and multiple binder systems)
4. Break the dependency on Spring Boot `RabbitAutoConfiguration` 

I realize this issue is probably not the highest priority thing to work on and we have scratched up quite a few complexities and unknowns in the above thread, BUT.... I already have put together something for item #4 and will link the changes in my userbranch for posterity here shortly. 

If I can get some direction, I would be happy to work on any of the above. I am also happy to just move along until and revisit this when the time is right. Just let me know. Thanks.

**Comment by garyrussell** [comment]
cc/ @sabbyanandan @olegz @sobychacko 

Thoughts?

**Comment by sabbyanandan** [comment]
The `java-cfenv` adjustment, I agree; it is high time we swap it out. At least when deploying SCSt apps from SCDF to CF/TAS, we strictly only rely on `java-cfenv`, and it has been that way for the last 4+ minor releases of SCDF.

The Spring Cloud Connectors and the associated auto-reconfiguration magic is entirely only a thing in CF/TAS deployments, so AFA the service-binding (and autoconfiguration via `java-cfenv`) functionality continues to work, I don't see any reason why we cannot change it already.

We cannot do this in a patch release, I agree, and it can be scoped for 3.2, perhaps. @olegz: WDYT?

**Comment by sobychacko** [comment]
The new apps have been using the `java-cfenv` library for a while now. We can certainly switch to this one, but as @sabbyanandan said, we may only want to do it on `3.2.0` version of the binder.

**Comment by bono007** [comment]
This was the thought for item 4) 
 
- https://github.com/spring-projects/spring-boot/pull/26866
- https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/pull/322

**Comment by bono007** [comment]
I started to dig into Spring Cloud Dataflow (SCDF) in order to understand the bigger picture a bit more. In doing so I noticed that SCDF has [dependencies](https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/spring-cloud-dataflow-server/src/main/java/org/springframework/cloud/dataflow/server/single/DataFlowServerApplication.java#L20) on several Spring Boot autoconfigs:

- org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
- org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
- org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
- org.springframework.boot.autoconfigure.session.SessionAutoConfiguration

@wilkinsona what are your thoughts on this? Is SCDF a core application that has been given the ok to use SB auto-configs?

**Comment by wilkinsona** [comment]
Those look fine to me as the auto-configuration classes are only being referenced to exclude them. Referencing for ordering (`@AutoConfigureBefore` and `@AutoConfigureAfter`) is fine too.

**Comment by bono007** [comment]
Ha!  It is excludes, not imports. I was deep in the middle of digesting
several (new to me) spring-cloud and cloudfoundry repos and missed that
detail. Otherwise  i would not have made that comment as its perfectly
expected for consumers to exclude auto-configs.

Sorry for the false alarm.

**Comment by bono007** [comment]
> The new apps have been using the java-cfenv library

@sobychacko I am assuming "The new apps" are the ones in https://github.com/spring-cloud/stream-applications ? If so, would the "old apps" be the ones in https://github.com/spring-cloud-stream-app-starters/rabbit/ ? 

In both cases, when `rabbit.own-connection: true` they construct a new ConnectionFactory using the SpringtBoot `RabbitAutoConfiguration`. @wilkinsona this is another instance of using the SB auto-config. 

**New apps:**
- https://github.com/spring-cloud/stream-applications/blob/0415c2c6279c4398c78e94ac1eaf420641bd0720/functions/consumer/rabbit-consumer/src/main/java/org/springframework/cloud/fn/consumer/rabbit/RabbitConsumerConfiguration.java#L154
- https://github.com/spring-cloud/stream-applications/blob/main/functions/supplier/rabbit-supplier/src/main/java/org/springframework/cloud/fn/supplier/rabbit/RabbitSupplierConfiguration.java#L196

**Old apps:** 
- https://github.com/spring-cloud-stream-app-starters/rabbit/blob/66482cf818846f98e78107cdaca870790b020a78/spring-cloud-starter-stream-sink-rabbit/src/main/java/org/springframework/cloud/stream/app/rabbit/sink/RabbitSinkConfiguration.java#L116
- https://github.com/spring-cloud-stream-app-starters/rabbit/blob/66482cf818846f98e78107cdaca870790b020a78/spring-cloud-starter-stream-source-rabbit/src/main/java/org/springframework/cloud/stream/app/rabbit/source/RabbitSourceConfiguration.java#L161

**Comment by bono007** [comment]
Can we actually deprecate and remove the support for the Spring Cloud Connector (SCC) config in `RabbitServiceAutoConfiguration` (RSAC) ? The project is in maintenance mode but I still see current [Tanzu docs](https://tanzu.vmware.com/developer/guides/spring/spring-cloud-connectors) on using the connector. If we removed support here, would the auto-reconfiguration buildpack handle this case properly by rewriting the rabbit connection factory using the service connector? 

If we end up having to keep the SCC config here in the RSAC then I don't think the the RSAC really needs to be "re-worked" other than breaking the direct dependence on SB RabbitAutoConfiguration. It currently handles all of the cases:

**Cloud profile w/ only SCC used:** 
This config will run: https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/9f55169515b30d57f23b5581050093ab5e4c0674/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/config/RabbitServiceAutoConfiguration.java#L129

**Cloud profile w/ CFENV being used:**
Because [CFENV will bomb](https://github.com/pivotal-cf/java-cfenv/blob/master/java-cfenv-boot/src/main/java/io/pivotal/cfenv/spring/boot/AmqpCfEnvProcessor.java#L47) if it finds SCC on the classpath, we are guaranteed that this config will run: https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/9f55169515b30d57f23b5581050093ab5e4c0674/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/config/RabbitServiceAutoConfiguration.java#L183

**Non-cloud profile**
This config will run: https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/9f55169515b30d57f23b5581050093ab5e4c0674/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/config/RabbitServiceAutoConfiguration.java#L198

**Comment by wilkinsona** [comment]
>  this is another instance of using the SB auto-config

Sub-classing auto-configurations like that isn't supported and should be avoided. The [documentation](https://docs.spring.io/spring-boot/docs/2.3.x/reference/htmlsingle/#using-boot-disabling-specific-auto-configuration) contains this cautionary note:

> Even though auto-configuration classes are public, the only aspect of the class that is considered public API is the name of the class which can be used for disabling the auto-configuration. The actual contents of those classes, such as nested configuration classes or bean methods are for internal use only and we do not recommend using those directly.

This has always been Boot's position but the note wasn't [added](https://github.com/spring-projects/spring-boot/commit/47a9bb1c0e3d5758bc5358f2953d93f1412748db) to the documentation until Spring Boot 2.1.8 in August 2019.

**Comment by bono007** [comment]
I think we can create lightweight Rabbit ConnectionFactory factory in spring-cloud-stream-binder-rabbit and use that in the binder config as well as in the Streams apps (above links). 

"Lightweight" in the sense that it would not support all of the configuration knobs that the SB config does, but just the ones required and currently advertised in the binder and the streams apps Rabbit consumer/sinks. 

I will submit a proposal for the above the next time I have some spare cycles but will probably not get back to this for a few days.
