### ISSUE TITLE
Question: Why dead-letter-exchange configuration is shared in RabbitCommonProperties?

### ISSUE THREAD

**Issue by faisalqublan** [spring-cloud/spring-cloud-stream-binder-rabbit#362]
Is there any difference between declaring the dlx configuration in the producer vs in the consumer side? considering that retires are NOT needed

I asked ChatGPT and always state that dlx configuration should be declared on both sides (producer and consumer) as a best practice and to avoid message losses.

**Comment by garyrussell** [comment]
Don't use issues to ask questions, they are for reporting bugs or asking for new features; use the discussions tab or ask on Stack Overflow.

It depends on how you deploy your apps; Spring Cloud Data Flow, for example, always deploys a stream right to left so that the consumers are always deployed before producers.

It is only necessary to declare them on the producer side if, for some reason, you want to deploy a producer first (and know the consumer group ahead of time, and specified using the `requiredGroups` property).
