### ISSUE TITLE
Clarify usage of of autoBindDlq and republishToDlq

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-stream-binder-rabbit#4]
It is not clear to me why there are two separate properties related to DLQ handling.  If autoBindDlq=true but republishtoDlq=false then you have not really done anything other than create empty rabbitmq infrastructure to handle error messages, the app won't publishing anything to the exchange.  Can we have instead an `enableDlq` option that would service as a single flag for the functionality that currently sits behind these two properties.

**Comment by garyrussell** [comment]
>autoBindDlq=true but republishtoDlq=false then you have not really done anything other than create empty rabbitmq infrastructure to handle error messages, the app won't publishing anything to the exchange.

They really are two different things.

`autoBindDlq=true` means create the DLX/DLQ and configure the main queue with arguments to route rejected messages to the DLX/DLQ (when `republishtoDlq=false`).

`republishtoDlq=true` means instead of rejecting messages (so Rabbit routes to the DLX/DLQ) the binder republishes the message to the DLX/DLQ, but adding additional diagnostic information (such as the stack trace) in headers.

I guess we can improve the docs?

**Comment by sabbyanandan** [comment]
@markpollack: Thoughts on Gary's suggestion?

**Comment by sabbyanandan** [comment]
@markpollack - perhaps this PR fixes it: https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/pull/12?

**Comment by mbogoevici** [comment]
Closing this for now as current documentation covers it.
