### ISSUE TITLE
Is there any example show how to use bindingRoutingKey to do wildcard subscription?

### ISSUE THREAD

**Issue by jiangyuhe123** [spring-cloud/spring-cloud-stream-binder-rabbit#59]
We are using the latest version of spring cloud stream which is Brooklyn SR3, and we found the define of bindingRoutingKey in Producer doesn't work as expected, although bindQueue is true and we are non-partitioned and requiredGroups  is defined. 
Is there any example to show how to work with bindingRoutingKey in both Producer and Consumer? Many thanks.

**Comment by garyrussell** [comment]
Can you provide more details - what you are setting the properties to, and what you mean by "doesn't work as expected" - i.e. what are you expecting and what is happening?

**Comment by jiangyuhe123** [comment]
Hi Gary,

You can refer to this post for more details https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/57, it is reported by our engineer. 

It turns out currently the change of bindingRoutingKey for Producer doesn't work, it still use the same value as exchange name, but routingKeyExpression can work if it is non-partitioned. So we wonder if our configure is not set correctly and seek for some examples of how to use bindingRoutingKey.

Thanks for the reply.
Michael

**Comment by marvinrichter** [comment]
A wildcard routing key would only make sense for a consumer channel. To do this you have to set `spring.cloud.stream.rabbit.bindings.<channelName>.consumer.bindingRoutingKey=maintopic.subtopic.#`
Then your producer would set it's routing key via `spring.cloud.stream.rabbit.bindings.<channelName>.producer.routingKeyExpression='maintopic.subtopic.subsubtopic'`.

Note the single quotation in 'maintopic.subtopic.subsubtopic' which is necessary for static routing keys because this config is interpreted as a SpEL expression.

**Comment by garyrussell** [comment]
Thanks @marvinrichter ; @jiangyuhe123 please also see my comment on #57.
